channels:
  - bioconda
  - r
  - defaults
  - conda-forge
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - backcall=0.2.0
  - biopython=1.78
  - blast=2.16.0
  - bottleneck=1.4.2
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.7.15
  - comm=0.2.2
  - curl=8.13.0
  - debugpy=1.8.14
  - decorator=5.2.1
  - entrez-direct=22.4
  - executing=2.2.0
  - gatk4=4.6.2.0
  - importlib-metadata=8.6.1
  - ipykernel=6.29.5
  - ipython=8.12.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.7.2
  - krb5=1.21.3
  - libblas=3.9.0
  - libcblas=3.9.0
  - libcurl=8.13.0
  - libcxx=20.1.3
  - libedit=3.1.20230828
  - libev=4.33
  - libexpat=2.7.0
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libidn2=2.3.4
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libnghttp2=1.64.0
  - libopenblas=0.3.29
  - libsodium=1.0.20
  - libsqlite=3.49.1
  - libssh2=1.11.1
  - libunistring=0.9.10
  - libzlib=1.3.1
  - llvm-openmp=14.0.6
  - matplotlib-inline=0.1.7
  - ncbi-vdb=3.2.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numexpr=2.10.1
  - numpy=1.26.4
  - openjdk=17.0.14
  - openssl=3.5.2
  - packaging=25.0
  - pandas=2.2.3
  - parso=0.8.4
  - perl=5.32.1
  - perl-archive-tar=2.40
  - perl-carp=1.38
  - perl-common-sense=3.75
  - perl-compress-raw-bzip2=2.201
  - perl-compress-raw-zlib=2.202
  - perl-encode=3.21
  - perl-exporter=5.72
  - perl-exporter-tiny=1.002002
  - perl-extutils-makemaker=7.3506
  - perl-io-compress=2.201
  - perl-io-zlib=1.14
  - perl-json=4.10
  - perl-json-xs=4.03
  - perl-list-moreutils=0.430
  - perl-list-moreutils-xs=0.430
  - perl-parent=0.236
  - perl-pathtools=3.75
  - perl-scalar-list-utils=1.69
  - perl-storable=3.15
  - perl-types-serialiser=1.01
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.0
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - prompt_toolkit=3.0.51
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.9.22
  - python-dateutil=2.9.0post0
  - python-tzdata=2025.2
  - python_abi=3.9
  - pytz=2024.1
  - pyzmq=26.4.0
  - readline=8.2
  - rpsbproc=0.5.0
  - seqkit=2.10.1
  - seqtk=1.5
  - setuptools=75.8.0
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.4.2
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - tzdata=2025a
  - wcwidth=0.2.13
  - wget=1.21.4
  - wheel=0.45.1
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
